package commands

const pythonInit = `
echo '# DO NOT EDIT THIS FILE. This file will be overwritten when re-running sh generate.sh.\n\n' > ./pytypes/__init__.py

for file in $(ls ./pytypes | grep -v __init__.py | grep -v client_support.py)
do 
    if [ "${file#*.}" = "py" ]; then 
        echo from .${file%.*} import ${file%.*} >> ./pytypes/__init__.py
    fi
done

echo from .client_support import to_dict >> ./pytypes/__init__.py
echo from .client_support import to_json >> ./pytypes/__init__.py

echo '# DO NOT EDIT THIS FILE. This file will be overwritten when re-running sh generate.sh.\n\n' > ./handlers/__init__.py

for file in $(ls ./handlers | grep -v __init__.py)
do 
    if [ "${file#*.}" = "py" ]; then 
        echo from .${file%.*} import ${file%.*} >> ./handlers/__init__.py
    fi
done
`

const gunicornStart = `#!/bin/bash
EXEC=%s
APP_HOME=$(cd "$(dirname $0)/..";pwd)
CMD="gunicorn"
nohuplog="$APP_HOME/var/log/nohup.out"
nohup $CMD -c $APP_HOME/etc/conf/gunicorn.pyc --chdir $APP_HOME app:app >> $nohuplog 2>&1 &
`

const gunicornStop = `#!/bin/bash
EXEC=%s
APP_HOME=$(cd "$(dirname $0)/..";pwd)
CMD="kill -TERM"
PID=$(cat $APP_HOME/var/run/gunicorn.pid)
$CMD $PID
`

const venvSetup = `#!/bin/bash

APP_HOME=$(cd "$(dirname $0)/..";pwd)
VENV_HOME=$APP_HOME/venv
echo "Create python virtualenv on [$VENV_HOME]"
PY_CMD=python
OS=$(uname -s)
if [ "$OS" = "Linux" ]; then
    PY_CMD=python3
fi

if [ ! -d "$VENV_HOME" ]; then
    $PY_CMD -m venv $VENV_HOME
fi

if [ "$OS" = "Darwin" ] || [ "$OS" = "Linux" ]; then
    . $VENV_HOME/bin/activate
else
    . $VENV_HOME/Scripts/activate
fi

pip install autopep8

if [ "$OS" = "Darwin" ]; then
    echo "\n    Use [. $VENV_HOME/bin/activate] enter python virtualenv\n"
elif [ "$OS" = "Linux" ]; then
    echo -e "\n    Use [. $VENV_HOME/bin/activate] enter python virtualenv\n"
else
    echo -e "\n    Use [. $VENV_HOME/Scripts/activate] enter python virtualenv\n"
fi
`

const pyGitIgnorePattern = `dist/*.zip
dist/*.tgz
runtime/bin/%s
runtime/venv
*.pyc
`
