package commands

const pythonInit = `
echo '# DO NOT EDIT THIS FILE. This file will be overwritten when re-running sh generate.sh.\n\n' > ./pytypes/__init__.py

for file in $(ls ./pytypes | grep -v __init__.py | grep -v client_support.py)
do 
    if [ "${file#*.}" = "py" ]; then 
        echo from .${file%.*} import ${file%.*} >> ./pytypes/__init__.py
    fi
done

echo from .client_support import to_dict >> ./pytypes/__init__.py
echo from .client_support import to_json >> ./pytypes/__init__.py

echo '# DO NOT EDIT THIS FILE. This file will be overwritten when re-running sh generate.sh.\n\n' > ./handlers/__init__.py

for file in $(ls ./handlers | grep -v __init__.py)
do 
    if [ "${file#*.}" = "py" ]; then 
        echo from .${file%.*} import ${file%.*} >> ./handlers/__init__.py
    fi
done
`

const gunicornStart = `
#!/bin/bash
EXEC=%s
APP_HOME=$(cd "$(dirname $0)/..";pwd)
CMD="gunicorn"
nohuplog="$APP_HOME/var/log/nohup.out"
nohup $CMD -c $APP_HOME/etc/conf/gunicorn.pyc --chdir $APP_HOME app:app >> $nohuplog 2>&1 &
`

const gunicornStop = `
#!/bin/bash
EXEC=%s
APP_HOME=$(cd "$(dirname $0)/..";pwd)
CMD="kill -TERM"
PID=$(cat $APP_HOME/var/run/gunicorn.pid)
$CMD $PID
`
